language: node_js
node_js:
  - "10"
cache: npm

sudo: required
dist: xenial

notifications:
  email:
    recipients:
      - shihaoyang129@gmail.com # 设置通知邮件
    on_success: change
    on_failure: always

before_install:
  - sudo mkdir -p /usr/share/fonts/opentype/
  - sudo mv ./guide-book/fonts/AdobeFangsongStd-Regular.otf /usr/share/fonts/opentype/
  - sudo mv ./guide-book/fonts/AdobeHeitiStd-Regular\ \(v5.010\).otf /usr/share/fonts/opentype/
  - sudo mv ./guide-book/fonts/AdobeKaitiStd-Regular\ \(v5.010\).otf /usr/share/fonts/opentype/
  - sudo mv ./guide-book/fonts/AdobeSongStd-Light\ \(v5.010\).otf /usr/share/fonts/opentype/
  - sudo mkfontscale
  - sudo mkfontdir
  - sudo fc-cache -fv
  - sudo fc-list :lang=zh

install:
  - npm install -g gitbook-cli
  - npm install -g prismjs
  - gitbook install

script:
  - gitbook build

after_script:
  - cd _book
  - git init
  - git remote add origin https://$REF
  - git add .
  - git commit -m "Updated By Travis-CI With Build $TRAVIS_BUILD_NUMBER For Github Pages"
  - git push --force --quiet "https://$TOKEN@$REF" master:gh-pages

branches:
  only:
    - master

env:
  global:
    - REF=github.com/hadyang/interview.git # 设置 github 地址
